# Classificar os ativos

Esse notebook tem como objetivo adicionar uma coluna de classificação de ativos para cada um dos investimentos feitos.

In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('../data/raw/PosicaoIntelli.csv')
df.head()

,CONTA,FINANCEIRO,QUANTIDADE,NOME ATIVO,TIPO DE ATIVO,PERFIL DA CARTEIRA
0,27,16278.264089,16.0,CRI CDIE,TITULOS RF PRIVADOS BRASIL,Moderado
1,27,25081.618073,25.0,CRA CDIE,TITULOS RF PRIVADOS BRASIL,Moderado
2,27,47046.248881,49.0,CRA IPCA,TITULOS RF PRIVADOS BRASIL,Moderado
3,27,36331.476685,35.0,RRRP13 IPCA,DEBENTURES BRASIL,Moderado
4,27,18995.623640,20.0,EEELA1 IPCA,DEBENTURES BRASIL,Moderado

Note como o dataframe possui uma coluna "TIPO DE ATIVO", que agrupa os ativos em grupos que possuem o mesmo nível de risco. O próximo passo é descobrir quais são todos esses tipos e classificar eles manualmente.

In [3]:
tipos_unicos = df['TIPO DE ATIVO'].unique()
print(tipos_unicos)

['TITULOS RF PRIVADOS BRASIL' 'DEBENTURES BRASIL' 'ACOES BRASIL'
 'TITULOS RF PUBLICOS BRASIL' 'CUPOM DE IPCA FUTURO          '
 'CDI DE UM DIA - FUTURO        ' 'AÇÕES INTERNACIONAIS'
 'TITULOS RF INTERNACIONAL' 'OPÇÃO S/ DISPONÍVEL DE CPM'
 'CUPOM CAMBIAL FUTURO          ' 'OPÇÃO S/ DISPONÍVEL DE IDI'
 'DOLAR FUTURO                  ' 'WDOF                          '
 'Microcontrato de Índice S&P500' 'MINI INDICE BOVESPA FUTURO    '
 'OPCOES S/ ACOES BRASIL' 'INDICE BOVESPA FUTURO         '
 'OPÇÃO FLEXÍVEL DOLAR' 'DISPONIVEL DE OURO 250 GRAMAS' 'TIME DEPOSIT'
 'OPÇÕES S/ AÇÕES INTERNACIONAIS' 'CAFE ARABICA FUTURO           '
 'BOI GORDO FUTURO              ' 'EUROBONDS' 'OPÇÃO S/ DISPONÍVEL DE DOL'
 'ADRS' 'OPÇÃO FLEXÍVEL AÇÃO BR' 'OPÇÃO S/ FUTURO DE BGI'
 'Dólar dos Estados Unidos da Am' 'ISPF                          '
 'OPÇÃO S/ FUTURO DE ISP' 'T10F                          '
 'Coroa Sueca por Dólar dos Esta' 'Coroa Norueguesa por Dólar dos'
 'Franco Suíço por Dólar dos Est' 'Peso Mexicano por Dólar dos Es'
 'Iene Japonês por Dólar dos Est' 'Iuan Chinês por Dólar dos Esta'
 'Peso Chileno por Dólar dos Est' 'Dólar Canadense por Dólar dos '
 'Rande da África do Sul por Dól' 'CCMF                          '
 'FUTURO DE SUZB3 FUTURO ' 'FUTURO DE RENT3 FUTURO '
 'FUTURO DE PETR4 FUTURO jan2019' 'Futuro de Bitcoin FUTURO mai20'
 'FUTURO SMALL FUTURO dez2024' 'FUTURO DE ITSA4 FUTURO '
 'Futuro de EQTL3 FUTURO mar2025' 'FUTURO DE PRIO3 FUTURO mar2025'
 'OURO 10 GRAMAS' 'OURO 0.225GR' 'OPÇÃO FLEXÍVEL ÍNDICE'
 'Indice Euro Stoxx 50 FUTURO' 'OPÇÃO FLEXÍVEL COM'
 'FUTURO DE VALE3 FUTURO fev2019' 'OPÇÃO FLEXÍVEL AÇÃO INDINT'
 'OPÇÃO S/ FUTURO DE D14' 'OPÇÃO S/ FUTURO DE D13'
 'FUTURO DE ITUB4 FUTURO nov2022' 'FUTURO DE BBAS3 FUTURO '
 'FUTURO DE ABEV3 FUTURO nov2022' 'FUTURO DE BBDC4 FUTURO '
 'FUTURO DE MGLU3 FUTURO ' 'Contrato Futuro de RADL3 FUTUR'
 'FUTURO DE HYPE3 FUTURO fev2019' 'FUTURO DE PSSA3 FUTURO fev2019'
 'WEUF                          ']

Uma vez descoberto quais são todos os tipos de ativos existentes nos dados, utilizando o auxilio da PerplexityAI, classificamos cada um dos tipos de fundos em Conservador, Moderado ou Sofisticado. Assim, criamos um csv chamado "Barema".

In [ ]:
barema = pd.read_csv('../data/raw/classificacao_de_tipos.csv')
barema.tail()

                         Ativo Classificacao
76      OPÇÃO S/ FUTURO DE D14   Sofisticado
77      OPÇÃO S/ FUTURO DE ISP   Sofisticado
78      OPÇÃO S/ FUTURO DE D13   Sofisticado
79  OPÇÃO S/ DISPONÍVEL DE IDI   Sofisticado
80  OPÇÃO FLEXÍVEL AÇÃO INDINT   Sofisticado

Uma vez com um barema definido, basta alocarmos as respectivas classificações para cada tipo de ativo nas linhas do dataframe original.

In [5]:
df['TIPO DE ATIVO'] = df['TIPO DE ATIVO'].str.strip()
barema['Ativo'] = barema['Ativo'].str.strip()

mapeamento_dict = dict(zip(barema['Ativo'], barema['Classificacao']))

df['CLASSIFICACAO DO ATIVO'] = df['TIPO DE ATIVO'].map(mapeamento_dict)
df.head()

,CONTA,FINANCEIRO,QUANTIDADE,NOME ATIVO,TIPO DE ATIVO,PERFIL DA CARTEIRA,CLASSIFICACAO DO ATIVO
0,27,16278.264089,16.0,CRI CDIE,TITULOS RF PRIVADOS BRASIL,Moderado,Moderado
1,27,25081.618073,25.0,CRA CDIE,TITULOS RF PRIVADOS BRASIL,Moderado,Moderado
2,27,47046.248881,49.0,CRA IPCA,TITULOS RF PRIVADOS BRASIL,Moderado,Moderado
3,27,36331.476685,35.0,RRRP13 IPCA,DEBENTURES BRASIL,Moderado,Moderado
4,27,18995.623640,20.0,EEELA1 IPCA,DEBENTURES BRASIL,Moderado,Moderado

Agora com a coluna Classificação do Ativo (classificada de acordo com o Tipo de Ativo), basta apenas verificar se todos os ativos estão de fato com uma classificação

In [6]:
print(df['CLASSIFICACAO DO ATIVO'].value_counts())


print("\nQuantidade de valores nulos em CLASSIFICACAO DO ATIVO:")
print(df['CLASSIFICACAO DO ATIVO'].isna().sum())


print("\nExemplos de registros com classificação nula:")
print(df[df['CLASSIFICACAO DO ATIVO'].isna()].head())


missing_mappings = set(df[df['CLASSIFICACAO DO ATIVO'].isna()]['TIPO DE ATIVO'].unique())
print("\nTipos de ativos sem classificação no barema:")
for asset_type in missing_mappings:
    print(f"- {asset_type}")

CLASSIFICACAO DO ATIVO
Moderado       204237
Sofisticado     48843
Conservador     33066
Name: count, dtype: int64

Quantidade de valores nulos em CLASSIFICACAO DO ATIVO:
0

Exemplos de registros com classificação nula:
Empty DataFrame
Columns: [CONTA, FINANCEIRO, QUANTIDADE, NOME ATIVO, TIPO DE ATIVO, PERFIL DA CARTEIRA, CLASSIFICACAO DO ATIVO]
Index: []

Tipos de ativos sem classificação no barema:

Como é possível observar, nenhum valor de classificação do ativo foi dado como nulo, logo, todos os ativos foram perfeitamente classificados